
```{r libraries}
library(tidyverse)
library(sf)
library(readr)
```

```{r readingdata}

## Reading the Data ##

clean_businesses_count <- read_csv("data/clean_businesses_count.csv")
clean_businesses_final <- read_csv("data/clean_businesses_final.csv")
clean_dispensaries_count <- read_csv("data/clean_dispensaries_count.csv")
clean_dispensaries_final <- read_csv("data/clean_dispensaries_final.csv")
merged_data <- read_csv("data/merged_data.csv")
merged_data_wclass <- read_csv("data/merged_data_wclass.csv")

```

### Busisnesses
- background on businesses
- just relating what is noticed
- reason for data set
- describe distribution if we can
```{r businesses}
library(skimr)
library(modelsummary)

#Numerical Summary
look_at_businesses <-
  datasummary_skim(clean_businesses_final)
look_at_businesses

#Numerical summary
count_businesses_summary <-
  datasummary_skim(clean_businesses_count)
count_businesses_summary

#Numerical Correlation (No categorical avaliable)
businesses_correlation <-
  datasummary_correlation(clean_businesses_final)
businesses_correlation

```

### Dispensaries
- background on dispensary data:
- relaying the info on what is noticed
- reason for data set
- describe distribution if we can
```{r dispensaries}
# Numerical summary
look_at_dispensaries <-
  datasummary_skim(clean_dispensaries_final)
look_at_dispensaries

# Numerical Correlation
dispensaries_correlation <-
  datasummary_correlation(clean_dispensaries_final)
dispensaries_correlation
```

### Merged Data

```{r}
merged_data_wclass_summary <-
  datasummary_skim(merged_data_wclass)
merged_data_wclass_summary
 
summary(merged_data_wclass)
```

```{r}
# scatter plot distribution of 10 variables, we can edit which variables we want to use
# to save as PDF pdf(file="saving_plot1.pdf")
# insert plot here
# to save as PDF dev.off()

plot(merged_data_wclass, col="darkgreen")

```

